---
title: "R Notebook"
output: html_notebook
---


```{r}
library(affy)
library(limma)
library(tibble)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(ggrepel)
library(readr)
library(limma)
library(pheatmap)
```


```{r}
library(GEOquery)
## change my_id to be the dataset that you want.
my_id <- "GSE34855"
gse <- getGEO(my_id)
```


```{r}
length(gse)
```


```{r}
gse1 <- gse[[1]]
gse1
```


```{r}
pData(gse1) ## print the sample information
```


```{r}
fData(gse1) ## print the gene annotation
```



```{r}
exprs(gse1) ## print the expression data
```


```{r}
summary(exprs(gse1))
```



```{r}
boxplot(exprs(gse1), outline = FALSE)
```



```{r}
sampleInfo <- pData(gse1)
sampleInfo
```


```{r fig.height=15, fig.width=15}
corMatrix <- cor(exprs(gse1), use = "c")
pheatmap(corMatrix)
```



```{r}
rownames(sampleInfo)
```



```{r}
colnames(corMatrix)
```



```{r}
rownames(sampleInfo) <- colnames(corMatrix)
```



```{r}
as.numeric(corMatrix)
```


```{r}
pca <- prcomp(t(exprs(gse1)))
```



```{r}
pca
```



```{r}
cbind(sampleInfo, pca$x) %>%
ggplot(aes(x = PC1, y = PC2, col = source_name_ch1, label = paste("cells", geo_accession))) + geom_point() + geom_text_repel()
```



```{r}
full_output <- cbind(fData(gse1), exprs(gse1))
write_tsv(full_output, file = "/Users/anb/Documents/CMEB-Lab/TGCT-DR/GSE34855/GSE34855_full_output.tsv")
```



```{r}
design <- model.matrix(~0 + sampleInfo$source_name_ch1)
design
```



```{r}
colnames(design) <- c("EC", "ES")
```



```{r}
design
```


```{r}
summary(exprs(gse1))

## calculate median expression level
cutoff <- median(exprs(gse1))

## TRUE or FALSE for whether each gene is "expressed" in each sample
is_expressed <- exprs(gse1) > cutoff

## Identify genes expressed in more than 2 samples

keep <- rowSums(is_expressed) > 2

## check how many genes are removed / retained.
table(keep)

## subset to just those expressed genes
gse1 <- gse1[keep, ]
```


```{r}
fit <- lmFit(exprs(gse1), design)
head(fit$coefficients)
```


```{r}
contrasts <- makeContrasts(EC - ES, levels = design)

## can define multiple contrasts
## e.g. makeContrasts(Group1 - Group2, Group2 - Group3,....levels=design)

fit2 <- contrasts.fit(fit, contrasts)
```


```{r}
fit2 <- eBayes(fit2)
```


```{r}
topTable(fit2)
```


```{r}
topTable(fit2, coef = 1)
```


```{r}
decideTests(fit2)
```


```{r}
table(decideTests(fit2))
```


```{r}
anno <- fData(gse1)
anno
```




```{r}
sapply(strsplit((anno$gene_assignment), "/"), "[", 3)
```



```{r}
anno$Gene.Symbol <- sapply(strsplit((anno$gene_assignment), "/"), "[", 3)
```



```{r}
anno
```



```{r}
anno <- dplyr::select(anno, "Gene.Symbol")
fit2$genes <- anno
topTable(fit2)
```


```{r}
full_results <- topTable(fit2, number = Inf)
full_results <- tibble::rownames_to_column(full_results, "ID")
```


```{r}
full_results
```



```{r}
ggplot(full_results, aes(x = logFC, y = B)) + geom_point()
```



```{r}
## change according to your needs
p_cutoff <- 0.01
fc_cutoff <- 1.5

full_results %>%
  mutate(Significant = adj.P.Val < p_cutoff & abs(logFC) > fc_cutoff) %>%
  ggplot(aes(x = logFC, y = B, col = Significant)) + geom_point()
```


```{r}
p_cutoff <- 0.01
fc_cutoff <- 1.5
topN <- 25
options(ggrepel.max.overlaps = Inf)

full_results %>%
  mutate(Significant = adj.P.Val < p_cutoff &
           abs(logFC) > fc_cutoff) %>%
  mutate(Rank = 1:n(), Label = ifelse(Rank < topN, Gene.Symbol, "")) %>%
  ggplot(aes(x = logFC, y = B, col = Significant, label = Label)) + geom_point() + geom_text_repel(col = "black")
```


```{r}
p_cutoff <- 0.01
fc_cutoff <- 1.5

filter(full_results, adj.P.Val < 0.01, abs(logFC) > 1.5)
```

```{r}
filter(full_results, adj.P.Val < 0.01, abs(logFC) > 1.5) %>%
  write_tsv(file = "/Users/anb/Documents/CMEB-Lab/TGCT-DR/GSE34855/filtered_de_results_1-5fc_01pval.tsv")
```


```{r}
p_cutoff <- 0.01
fc_cutoff <- 1.5

genes_output <- filter(full_results, adj.P.Val < 0.01, abs(logFC) > 1.5)
```


```{r}
as.data.frame(genes_output$Gene.Symbol) %>%
  write_tsv(file = "/Users/anb/Documents/CMEB-Lab/TGCT-DR/GSE34855/filtered_de_results_1-5fc_01pval-genes.tsv")
```


```{r}
topN <- 25
##
ids_of_interest <- mutate(full_results, Rank = 1:n()) %>%
  filter(Rank < topN) %>%
  pull(ID)
```


```{r}
gene_names <- mutate(full_results, Rank = 1:n()) %>%
  filter(Rank < topN) %>%
  pull(Gene.Symbol)
```


```{r}
gene_matrix <- exprs(gse1)[ids_of_interest, ]
```


```{r fig.height=5, fig.width=15}
pheatmap(gene_matrix,
     labels_row = gene_names)
```

FILES EDITED IN PYTHON TO REMOVE DUPS

```{r}
df <- read_tsv("/Users/anb/Documents/CMEB-Lab/TGCT-DR/GSE34855/filtered_de_results_1-5fc_01pval_dup_dropped.tsv")
```

```{r}
write_tsv(as.data.frame(df$Gene.Symbol), file = "/Users/anb/Documents/CMEB-Lab/TGCT-DR/GSE34855/filtered_de_results_1-5fc_01pval_dup_dropped_genes_only.tsv", col_names = FALSE)
```

##### GENE SET ENRICHMENT ANALYSIS ######


```{r}
library(affy)
library(limma)
library(tibble)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(ggrepel)
library(readr)
library(limma)
library(pheatmap)
```


```{r}
library(pathview)
library(clusterProfiler)
library(enrichplot)
library(enrichplot)
library(ggplot2)
library(europepmc)
library(dplyr)
library(ggnewscale)
```



```{r}
organism <- "org.Hs.eg.db"
BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)
```


```{r}
upreg <- df[df$logFC >= 1, ]
downreg <- df[df$logFC <= -1, ]
```


```{r}
upreg_gene_list <- upreg$Gene.Symbol
downreg_gene_list <- downreg$Gene.Symbol
```


```{r}
write_tsv(as.data.frame(upreg_gene_list), file = "/Users/anb/Documents/CMEB-Lab/TGCT-DR/GSE34855/upreg_gene_list_1fc_05pval.tsv", col_names = FALSE)
write_tsv(as.data.frame(downreg_gene_list), file = "/Users/anb/Documents/CMEB-Lab/TGCT-DR/GSE34855/downreg_gene_list_1fc_05pval.tsv", col_names = FALSE)
```



```{r}
# we want the log2 fold change
original_gene_list <- df$logFC

# name the vector
names(original_gene_list) <- df$Gene.Symbol

# omit any NA values
gene_list <- na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list <- sort(gene_list, decreasing = TRUE)
```


```{r}
filtdf <- df %>% distinct(Gene.Symbol, .keep_all = TRUE)
```


```{r}
df <- filtdf
```


```{r}
df
```




```{r}
gse <- gseGO(geneList = gene_list,
             ont = "ALL",
             keyType = "SYMBOL",
             minGSSize = 3,
             maxGSSize = 800,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "none")
```



```{r, dotplot, echo=FALSE,fig.height=, dev='jpeg'}
require(DOSE)
dotplot(gse, showCategory = 10, split = ".sign") + facet_grid(.~.sign)
```











